### ISSUE TITLE
run hello_world_file.cpp in vs

### ISSUE THREAD

**Issue by zjydhr** [juj/vs-tool#10]
open \emscripten\tests\msvc10\tests_msvc10.sln in vs2010
hello_world.cpp can run in IE
hello_world_file.cpp can not, I guess the file "hello_world_file.txt" isn't load, how to do it in vs, like the "--preload-file xxx" in cmd

**Comment by juj** [comment]
It is possible to add --preload-file commands to VS solution properties, but these do not exist for the emscripten msvc10 tests (yet) due to difficulties with relative path handling from inside VS projects. You can try locally by adding "--preload-file C:\absolute\path\to\hello_world_file.txt@/" in VS properties to see if that resolves it.

**Comment by zjydhr** [comment]
Thanks for reply!! in VS properties? where?

**Comment by juj** [comment]
I mean right-click on a Visual Studio Project, choose Properties, Configuration Properties -> Emcc Linker -> Input -> "Preload Resource Files"

**Comment by juj** [comment]
Let me close this as solved. Thanks!
