### ISSUE TITLE
Error MSB6006 with emscripten exited with code 1

### ISSUE THREAD

**Issue by sirlocus** [juj/vs-tool#12]
Hello,

I'm trying to compile under visual studio 2010 with emscripten but I get an error that I can not fix.

this is the error msb6006 "emcc.bat" exited with code 1.

Node.js and Python 2.7.5 are under 32 bits. (After testing 64bits) I use LLVM and Clang recompiled with CMake bu also miingw64. My computer is Win 7 64 bit.

I did some tests as emcc - clear-cache runner.py test_hello_world

I made the bootstrapping emcc tests\hello_world.cpp -O3 test.html

I have complete error message

WindowsError: [Error 4317] LÆidentificateur dÆopÚration nÆest pas valide Traceback (most recent call last): File "C:\emscripten-master\emcc", line 1451, in final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args) File "C:\emscripten-master\tools\shared.py", line 1096, in emscripten assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output) AssertionError: Emscripten failed to generate .js: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\Microsoft.Cpp.Emscripten.Targets(121,5): error MSB6006: "emcc.bat" exited with code 1.

I paid attention to the problem in a slash the file .escripten and Global variables

Do you have any idea?

**Comment by juj** [comment]
I think this sounds like an issue I saw this week and fixed in the latest. The problem was in mixing 32-bit python with 64-bit clang, which gave trouble. It is best to install a toolchain with consistent bitness, but on my system mixed bitness works as well now after I disabled link-time incremental file tracking from Visual Studio. I'll close this for now, please reopen if the latest master branch still gives this issue. Thanks!
