### ISSUE TITLE
Emscripten outputs exe instead of js

### ISSUE THREAD

**Issue by vharron** [juj/vs-tool#25]
I updated to the latest vs-tool and Emscripten now generates exe files instead of js files.

Reverting to this version got it working again

commit e0d58f55c22d3c4a38a0237c3cf917a0b8903465
Author: Jukka Jylänki jujjyl@gmail.com
Date:   Thu Nov 21 12:01:44 2013 +0200

**Comment by juj** [comment]
Hmm, can you double-check this? That commit only changes a .txt file with a version number, it does not carry any functional changes?

Try checking Visual Studio project properties -> Configuration Properties -> General -> Target Extension. That should either say ".html" or ".js". If you manually migrated from Win32 platform configuration, it might have copied .exe into this field. (Migrating from Win32 config can need a number of manual cleanups like this, like removing WIN32 #ifdefs in the preprocessor).

**Comment by ArwedSchmidt** [comment]
This should be fixed right from the addin (see my other bug request). Any chance you can work on this ? If not, let me know and i'm gonna invest some time to find out how to fix your add in at least for Visual Studio 2010.

**Comment by MarkCallow** [comment]
I ran into this problem too. TargetExt is never set because the PropertyGroup in Emscripten/Microsoft.Cpp.Emscripten.props that sets TargetExt has a condition such that it is only entered if TargetExt is already .js or .html.  The following lines need to be changed. (I haven't cloned this project so can't send a pull request).

Line 20
- <PropertyGroup Condition="'$(TargetExt)' == '.js''>
- <PropertyGroup Condition="'$(TargetExt)' == '.js' or '$(ConfigurationType)' ==  'Application'">

Line 29
- <PropertyGroup Condition="'$(TargetExt)' == '.html''>
- <PropertyGroup Condition="'$(TargetExt)' == '.html' or '$(ConfigurationType)' ==  'Application'">

Please include the fix in the next release.

I should note that the project file I am using does not set TargetExt in any configuration. It relies on the platform default TargetExt for ConfigurationType "Application." So the issue cannot be blamed on migrating from a Win32 platform configuration.

**Comment by MarkCallow** [comment]
Damn. The modified code does not appear in the formatted message. Here it is again.

```
Line 20
- <PropertyGroup Condition="'$(TargetExt)' == '.js'">
+<PropertyGroup Condition="'$(TargetExt)' == '.js' or '$(ConfigurationType)' == 'Application'">

Line 29
- <PropertyGroup Condition="'$(TargetExt)' == '.js'">
+<PropertyGroup Condition="'$(TargetExt)' == '.js' or '$(ConfigurationType)' == 'Application'">
```

BTW, I don't see any property in Emcc Linker that selects whether to output the .html with js embedded or the separate .html and .js files. With this change, TargetExt is set to .html in a project that does not itself set TargetExt. So perhaps this change is not quite correct since, IIRC, Emscripten outputs separate files by default.

How do I select the kind of output?

**Comment by MarkCallow** [comment]
> How do I select the kind of output?

From looking at the emcc source, it is apparent that there is no longer any way to get it to generate a combined HTML wrapper + JS file. Specifying a .js output file results in just the JS file. Specifying a .html output file results in an html wrapper file & a separate JS file.

In the absence of any other property in vs-tool the way to select the output type is via the TargetExt setting. With my change this defaults to .html so I think the change is okay. Would really like to see it in the next vs-tool & emsdk releases.

**Comment by juj** [comment]
Thanks for pinging on this, now I see the issue and indeed, even the default values were .exe and .lib. This is fixed in the above commit. vs-tool 0.9.4 will have the fix.

The .html+.js emit behavior was changed last October for performance reasons. See https://groups.google.com/forum/#!searchin/emscripten-discuss/script$20async/emscripten-discuss/EuHMwqdSsEs/Az0MaYbEH80J .

**Comment by MarkCallow** [comment]
Fix worked for me. Thanks.
