### ISSUE TITLE
Is this project still working?

### ISSUE THREAD

**Issue by sbc100** [juj/vs-tool#49]
We have a whole bunch of tests in emscripten under `tests/msvc10/` which I have never run.  Are they expected to work?  

If this project is not functional anymore, perhaps we can mark it as such and remove those tests from emscripten?

**Comment by juj** [comment]
This project is no longer active.

I most often look at the most recent commit as the clue as to whether the project is still in active development. Therefore I wish not to push a new commit to this repo, which might make it look like there's been recent activity to it, but I hope the last commit date makes it clear, as last commit to this repo is from 2014.

Also the description states that this plugin works for Visual Studio 2010. Microsoft has since released VS2012, VS2013, VS2015, VS2017, VS2019 and now VS2022 is coming up, so I hope that together with the latest commit date should be good enough to let people know this is no longer up to date.

Back in the day there were some discussions with Microsoft to integrate Emscripten support to Visual Studio IDE, but those did not proceed, and in Emscripten repository CMake took over as the primary cross-platform build tool.

The directory tree tests/msvc10/ can be deleted from Emscripten. I doubt anyone uses that anymore.

**Comment by sbc100** [comment]
Thank!  (BTW, if you want to you can mark it as "archived" in github).

**Comment by juj** [comment]
oh that's perfect, I'll do that.
