### ISSUE TITLE
where is nodepause.bat

### ISSUE THREAD

**Issue by zjydhr** [juj/vs-tool#9]
My VS2010 runs the nodepause.bat and could not find the nodepause.bat in $(EMSCRIPTEN) where is it?

 <PropertyGroup Condition="'$(ConfigurationType)' == 'Application'">
    <LinkCompiled>true</LinkCompiled>
    <TargetExt>.js</TargetExt>
    <LocalDebuggerCommand>$(EMSCRIPTEN)\nodepause.bat</LocalDebuggerCommand>
    <TargetPath Condition="'$(TargetPath)' == ''">$([System.IO.Path]::Combine($(ProjectDir),$(OutDir)$(TargetName)$(TargetExt)))</TargetPath>
    <LocalDebuggerCommandArguments>$(TargetPath)</LocalDebuggerCommandArguments>
  </PropertyGroup>

**Comment by juj** [comment]
Thanks for reporting!

The goal of nodepause.bat is to run a generated .js file in node, but pause the output so that the user has time to read it. It is only used if a .js file is executed, but not if generating .html.

I fixed this now in https://github.com/juj/vs-tool/commit/5bb8c17fccface3a0a76e83bd4f7335703b5ad88 , does updating to that resolve the issue for you?

**Comment by zjydhr** [comment]
Thank you for reply!!

I got another problem, see in the attachment picture, thank you

Best Regards

2013/7/22 juj notifications@github.com

**Comment by juj** [comment]
This was resolved in the above commit.
